version: "3.8"

services:
  app:
    build: .
    container_name: demo-project-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: demo-project-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: demo-project-mysql
    environment:
      MYSQL_DATABASE: publicworks
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pw
      MYSQL_PASSWORD: pw
    ports:
      - "3306:3306"
    restart: unless-stopped
