spring:
  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USER}
    password: ${R2DBC_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt:
  secret: "CHANGE_ME_TO_A_SECURE_RANDOM_SECRET"
  expirationMs: 86400000   # 1â€¯day
